# Generated by Django 3.1.7 on 2021-05-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210514_1020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
