# Generated by Django 3.1.7 on 2021-06-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210528_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultprofilepic.png', null=True, upload_to=''),
        ),
    ]
